Import required libraries

In [6]:
import yfinance as yf
import pandas as pd
from pathlib import Path

Defining stock

Initially preparing model on one stock later expanding into many
Initially collecting historical data for Reliance Industries (NSE).

In [7]:
STOCK = "RELIANCE.NS"
START_DATE = "2015-01-01"

Downloading using yfinance

In [8]:
df = yf.download(STOCK, start=START_DATE, auto_adjust=False)

df.head()

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
Date,,,,,,
2015-01-01,189.125381,202.959000,203.896194,201.987518,202.593277,2963643
2015-01-02,188.624817,202.421829,204.821960,202.136108,203.004715,7331366
2015-01-05,186.558685,200.204575,203.644760,199.804550,202.296112,10103941
2015-01-06,178.091827,191.118393,199.553116,190.181198,198.867371,18627980
2015-01-07,181.968475,195.278610,196.307236,191.324127,191.346985,20720312

Clean the column structure and reset the date index

In [12]:
df.dropna(inplace=True)

In [13]:
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df.reset_index()

df.head()

Price,index,Date,Adj Close,Close,High,Low,Open,Volume
0,0,2015-01-01,189.125381,202.959000,203.896194,201.987518,202.593277,2963643
1,1,2015-01-02,188.624817,202.421829,204.821960,202.136108,203.004715,7331366
2,2,2015-01-05,186.558685,200.204575,203.644760,199.804550,202.296112,10103941
3,3,2015-01-06,178.091827,191.118393,199.553116,190.181198,198.867371,18627980
4,4,2015-01-07,181.968475,195.278610,196.307236,191.324127,191.346985,20720312

Save the original data as a raw CSV

In [14]:
raw_path = Path("../data/raw/RELIANCE.csv")

df.to_csv(raw_path,index=False)
print(f"Raw data saved to: {raw_path}")

Raw data saved to: ..\data\raw\RELIANCE.csv