# Naive Baseline Forecasting Model

A naive baseline forecasting model predicts that the future value of a time series will be identical to its most recently observed value

In [1]:
import pandas as pd
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

data_path = Path("../data/processed/RELIANCE_processed.csv")
df = pd.read_csv(data_path)

df.head()

,index,Date,Adj Close,Close,High,Low,Open,Volume,Target,lag1,lag2,lag3,lag5,lag10,Return,MA5,MA20,Volatility20
0,20,2015-01-30,194.951019,209.210754,212.868088,207.782104,212.582352,21746801,207.564957,212.445206,207.290649,203.221878,202.010391,197.553009,-0.015225,206.979782,200.206291,0.020023
1,21,2015-02-02,193.417374,207.564957,210.273666,207.027786,209.393616,19302710,214.319595,209.210754,212.445206,207.290649,202.730423,198.798798,-0.007867,207.946689,200.463448,0.020116
2,22,2015-02-03,199.711624,214.319595,215.062485,208.742157,208.742157,17092333,212.308060,207.564957,209.210754,212.445206,203.221878,201.073196,0.032542,210.166232,201.169199,0.021035
3,23,2015-02-04,197.837219,212.308060,215.736801,211.645172,214.662460,14072894,211.142288,214.319595,207.564957,209.210754,207.290649,206.422043,-0.009386,211.169714,202.228682,0.017932
4,24,2015-02-05,196.750900,211.142288,214.845322,209.747925,213.953857,12365643,207.987839,212.308060,214.319595,207.564957,212.445206,207.267792,-0.005491,210.909131,203.021866,0.017659

The baseline predicts that the next day's closing price will equal the current day closing price.

In [2]:
df["Date"] = pd.to_datetime(df["Date"])
df["Prediction"] = df["Close"]
df[["Date", "Close", "Target", "Prediction"]].head()

        Date       Close      Target  Prediction
0 2015-01-30  209.210754  207.564957  209.210754
1 2015-02-02  207.564957  214.319595  207.564957
2 2015-02-03  214.319595  212.308060  214.319595
3 2015-02-04  212.308060  211.142288  212.308060
4 2015-02-05  211.142288  207.987839  211.142288

Find Error of this model

In [3]:
results = df.dropna(subset=["Target", "Prediction"]).copy()
mae = mean_absolute_error(results["Target"],results["Prediction"])
rmse = np.sqrt(mean_squared_error(results["Target"],results["Prediction"]))
print(f"MAE:  ₹{mae:.2f}")
print(f"RMSE: ₹{rmse:.2f}")

MAE:  ₹9.51
RMSE: ₹14.32

Observations:
MAE:  ₹9.51
RMSE: ₹14.32